version: 2
jobs:
  machine:
    services:
      - docker
      - image: node:6
    working_directory: ~/MyFirstHackathon
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up --build
            docker run --network container:contacts \
              appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:8080/drivers/