version: 2
jobs:
  build:
    machine: true
    working_directory: ~/MyFirstHackathon
    environment:
      - NODE_ENV: "test"
    steps:
      - checkout
      - run:
          name: Upgrade docker
          command: |
            set -e
            curl -sSL https://download.docker.com/linux/static/edge/x86_64/docker-17.05.0-ce.tgz | sudo tar -xz /usr/bin/
            sudo service docker restart
      - run:
          name: Install Docker Compose
          command: |
            set -e
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Docker pull node image
          command: docker pull node:6
      - run:
          name: Docker pull mongo image
          command: docker pull mongo 
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Start container
          command: |
            set -x
            docker-compose up --build
test:
  docker:
    - image: node:6
    - image: mongo
  steps:
    - checkout
    - run:
        name: Test
        command: npm test
    
workflow:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master